[package]
name = "rustyController"
version = "0.1.0"
authors = ["Gabe <finkegabriel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stick = "0.7.1"